name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      # Advanced JSON configuration
      - name: Slash Command Dispatch (JSON)
        id: scd
        uses: peter-evans/slash-command-dispatch@v2

        with:
          token: ${{ secrets.PAT }}
          config: >
            [
              {
                "command": "hello-world-pr",
                "permission": "none",
                "repository": "zsluedem/rchain-bench-test",
                "issue_type": "pull-request"
              }
            ]